### ISSUE TITLE
Using GetGaiaCat.py

### ISSUE THREAD

**Issue by SeanPoints** [kslong/kred#23]
Just tried to execute GetGaiaCat.py from conda kred environment.  Ran into errors because the following packages were not installed inn my kred environment:
(1) photutils
(2) astroquery
(3) GaiaXPy
I installed those packages and can now see the usage information from command line.  Need to update README file with description of GetGaiaCat.py and list additional packages to install.

**Comment by kslong** [comment]
This is now done.
