### ISSUE TITLE
PhotComp.py

### ISSUE THREAD

**Issue by SeanPoints** [kslong/kred#25]
In PhotComp.py dev branch, commit version c3165e39948c77dfaaf4bdd00d273bd1286d3265

>PhotCompare.py ./DECam_SWARP2/LMC_c42/T07/LMC_c42_T07.N662.t800.fits

returns 
---
get_gaia: Getting data from RA Dec of  81.09811 -66.19779 and size of 0.46
INFO: Query finished. [astroquery.utils.tap.core]
Traceback (most recent call last):
  File "/home/points/bin/kred/py_progs/PhotCompare.py", line 618, in <module>
    steer(sys.argv)   
    ^^^^^^^^^^^^^^^
  File "/home/points/bin/kred/py_progs/PhotCompare.py", line 608, in steer
    do_one(one,gaia_cat_file)
  File "/home/points/bin/kred/py_progs/PhotCompare.py", line 574, in do_one
    gaia_file=get_gaia(ra, dec, size_deg,outroot,nmax=-1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/points/bin/kred/py_progs/PhotCompare.py", line 298, in get_gaia
    r.rename_column('teff_gspphot','teff')
  File "/home/points/anaconda/envs/kred/lib/python3.11/site-packages/astropy/table/table.py", line 3090, in rename_column
    raise KeyError(f"Column {name} does not exist")
KeyError: 'Column teff_gspphot does not exist'

If I uncomment print(r.info()) , I can see a column with name of 
"teff_val" and nothing called "teff_gspphot" It seems that I am querying a different catalog.

**Comment by SeanPoints** [comment]
I changed the line in the code to look for teff_val to rename instead of teff_gspphot.  That was successful but the catalog I query does not have corresponding entries for logg_gspphot or distance. So, we really need to figure out how to configure my system to search the appropriate database.

**Comment by kslong** [comment]
I don’t understand, Sean.  This was one of the files I ran successfully before we talked yesterday, and the results (modulo the scaling error) are in the xphot directory that I pushed to Box yesterday.

**Comment by SeanPoints** [comment]
I'm trying with another field.  Can you send version information of additional packages you installed to do this?

**Comment by kslong** [comment]
@SeanPoints please close this issue if it is no longer a concern.  If it is a concern, please provide a specific case, with as much detail as possible.
