### ISSUE TITLE
SetupTile

### ISSUE THREAD

**Issue by SeanPoints** [kslong/kred#30]
SetupTile.py  does not seem to include all of the detectors that overlap with a given tile.  As shown in the attached image, tiles 01 and 05 have significant  overlap that can be seen in the stars in common to both. In tile 01, the leftmost star has a gap below it that is not in tile 05 andthe region above the leftmost star is also missing detectors in the NE.

This omission of tiles also occurred in field SMC_c02 T16 where detector S31 was only included in the file list for 1 800s exposure with N673 even though there were 9 800s 673 MEF files for the field.

I was able to get aroud the issue by increasing the tile size in config/MC_tiles.txt from 0.67 deg to 0.87 deg and it picked up the other N673 S31 detectors.  It may be a simpler fix to adjust the tile sizes in MC_tiles.txt than go through SetupTiles.py and look at the logic for including detectors in a tile.

<img width="949" alt="Screen Shot 2024-09-28 at 4 29 45 PM" src="https://github.com/user-attachments/assets/50a4b457-bbe4-4b38-af98-bfe7b9708af6">

**Comment by kslong** [comment]
@SeanPoints   I can't quite figure out what you are saying here.  Does all of this refer to SMC_c02.  Can you provide more detail, e.g the files you expected to see "swarped" compared to the files that were swarped, as listed in the .in file.  

Although it is not one of your figures, your last note is about SMC_c02, Tile 16.
You say you only saw 1 800 s file for the S31 chip in SMC_c02, but I have also processed all of the fields not inclusing SMC_c02.  And when, I looked at the .in file in the SWARP2 directory for tile 16 of SMC_c02 and I see these files as inputs, which seems to be different from what you are reporting.  And I am using a normal configuration file, and processed the data limiting it to those files with less than 1.4 arsec seeing.

```
grep S31  SMC_c02_T16.N673.t800.in
/media/data3/DECam/kred_smc24/DECam_PREP2/SMC_c02/T16/c4d_211017_012613_ooi_N673_req_S31.fits
/media/data3/DECam/kred_smc24/DECam_PREP2/SMC_c02/T16/c4d_211017_014302_ooi_N673_req_S31.fits
/media/data3/DECam/kred_smc24/DECam_PREP2/SMC_c02/T16/c4d_211020_020026_ooi_N673_req_S31.fits
/media/data3/DECam/kred_smc24/DECam_PREP2/SMC_c02/T16/c4d_211020_023358_ooi_N673_req_S31.fits
/media/data3/DECam/kred_smc24/DECam_PREP2/SMC_c02/T16/c4d_211023_014134_ooi_N673_req_S31.fits
/media/data3/DECam/kred_smc24/DECam_PREP2/SMC_c02/T16/c4d_211023_015821_ooi_N673_req_S31.fits
/media/data3/DECam/kred_smc24/DECam_PREP2/SMC_c02/T16/c4d_211023_021511_ooi_N673_req_S31.fits
/media/data3/DECam/kred_smc24/DECam_PREP2/SMC_c02/T16/c4d_211023_023157_ooi_N673_req_S31.fits
```

There are a total of 48 files in the .in file.
