### ISSUE TITLE
SetupTiles fails on C48

### ISSUE THREAD

**Issue by kslong** [kslong/kred#8]
Sean reported and I confirm that SetupTiles.py failes on C48.  The problem appears to be that some of the Ha filter MEFS do not have the RAs and DECs of the image corners in the headers.  When this happens the det.tab file has Unknown in these positions, and then when SetupTiles.py reads this table, it sets the column type to string, and as a result cannot work on these numerically.

The long term solution is to get the MEFS reprocessed.

The short term solutions would be to use a number, e.g. -999 in stead of the word Unknown in the file as the bad value, and then SetupTiles.py would need to exclude such lines in this, or alternatively to calculate the corners our selves from the WCS for each extension.

**Comment by kslong** [comment]
This only affects 61 of 671 Ha images in this file.

(Note also Unknown is misspelled)

**Comment by kslong** [comment]
@SeanPoints  This should now be fixed on the overlap branch.  You will need to rerun MefSum.py again before SetupTiles.py.  MefSum now writes and extra file det_bad.tab if there are images without RAs and DECs in the headers, and writes only files that do have the RAs and DECs to the det.tab file.  Please close this issue once you have confirmed that it works for you.

**Comment by SeanPoints** [comment]
@kslong This is working for c48.

**Comment by SeanPoints** [comment]
Seems to be fixed. Shall we close the issue?
